spring:
  datasource:
    url: jdbc:mysql://localhost:3306/power?useSSL=true&characterEncoding=UTF-8
    username: root
    password: 123123
logging:
  level:
    io.github.firefang.power.server: debug