spring:
  application:
    name: power-api
  profiles:
    active: ${profile:dev}
server:
  port: 80
mybatis:
  type-aliases-package: io.github.firefang.power.server.entity.domain
power:
  login:
    type: token
    exclude-paths:
    - /swagger-resources/**
    - /webjars/**
    - /v2/**
    - /swagger-ui.html/**
  transaction:
    required-transaction-attributes:
    - login
    - logout
    - upsertBatch